version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
    env_file:
      - .backend.env.local
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
